/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yumXpress.gui;

import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import yumXpress.dao.CompanyDAO;
import yumXpress.dao.OrderDAO;
import yumXpress.dao.ProductDAO;
import yumXpress.pojo.PlaceOrderPojo;
import yumXpress.pojo.ProductPojo;
import yumXpress.utility.UserProfile;

/**
 *
 * @author prach
 */
public class OrderFoodFrame extends javax.swing.JFrame {

    private Map<String, String> companyMap;
    private List<ProductPojo> productList;
    private int listIndex;
    private JFrame showFrame;

    public OrderFoodFrame() {
        super("Order Food Frame");
        initComponents();
        setLocationRelativeTo(null);
        this.lblUserProfileName.setText("Hello " + UserProfile.getUserName().trim());
        loadCompanyNames();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblUserProfileName = new javax.swing.JLabel();
        btnMyAccount = new javax.swing.JButton();
        btnMyCart = new javax.swing.JButton();
        btnCancelOrder = new javax.swing.JButton();
        btnOrderHistory = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcCompanyNames = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblPrev = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();
        lblProductImage1 = new javax.swing.JLabel();
        lblProductImage2 = new javax.swing.JLabel();
        lblProductImage3 = new javax.swing.JLabel();
        lblProductName1 = new javax.swing.JLabel();
        lblProductName2 = new javax.swing.JLabel();
        lblProductName3 = new javax.swing.JLabel();
        lblProductImage4 = new javax.swing.JLabel();
        lblProductName4 = new javax.swing.JLabel();
        lblProductImage5 = new javax.swing.JLabel();
        lblProductImage6 = new javax.swing.JLabel();
        lblProductName5 = new javax.swing.JLabel();
        lblProductName6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpanel4.setBackground(new java.awt.Color(213, 228, 237));
        jpanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 156, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumXpress/icons/user.png"))); // NOI18N

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        lblUserProfileName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUserProfileName.setText("Hello @ null");

        btnMyAccount.setBackground(new java.awt.Color(35, 78, 105));
        btnMyAccount.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnMyAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnMyAccount.setText("My Account");
        btnMyAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyAccountActionPerformed(evt);
            }
        });

        btnMyCart.setBackground(new java.awt.Color(35, 78, 105));
        btnMyCart.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnMyCart.setForeground(new java.awt.Color(255, 255, 255));
        btnMyCart.setText("My Cart");
        btnMyCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyCartActionPerformed(evt);
            }
        });

        btnCancelOrder.setBackground(new java.awt.Color(35, 78, 105));
        btnCancelOrder.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnCancelOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelOrder.setText("Cancel Order");
        btnCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrderActionPerformed(evt);
            }
        });

        btnOrderHistory.setBackground(new java.awt.Color(35, 78, 105));
        btnOrderHistory.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnOrderHistory.setForeground(new java.awt.Color(255, 255, 255));
        btnOrderHistory.setText("Order History");
        btnOrderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderHistoryActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(35, 78, 105));
        btnBack.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMyCart, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMyAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOrderHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnBack))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(lblUserProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(lblUserProfileName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnMyAccount)
                .addGap(18, 18, 18)
                .addComponent(btnMyCart)
                .addGap(18, 18, 18)
                .addComponent(btnCancelOrder)
                .addGap(18, 18, 18)
                .addComponent(btnOrderHistory)
                .addGap(26, 26, 26)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 534));

        jLabel1.setFont(new java.awt.Font("Pristina", 1, 54)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 78, 105));
        jLabel1.setText("Order Food");
        jpanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 15, 287, 83));

        jcCompanyNames.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jcCompanyNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCompanyNamesActionPerformed(evt);
            }
        });
        jpanel4.add(jcCompanyNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(969, 58, 182, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(190, 169, 37));
        jLabel2.setText("Filter");
        jpanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 61, 52, -1));

        lblPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumXpress/icons/icons8-left-arrow-64 (1).png"))); // NOI18N
        lblPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPrevMouseClicked(evt);
            }
        });
        jpanel4.add(lblPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 255, -1, -1));

        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumXpress/icons/icons8-right-arrow-64 (1).png"))); // NOI18N
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNextMouseClicked(evt);
            }
        });
        jpanel4.add(lblNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(1105, 257, 73, -1));

        lblProductImage1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOrderProductMouseClicked(evt);
            }
        });
        jpanel4.add(lblProductImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 110, 176, 158));

        lblProductImage2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOrderProductMouseClicked(evt);
            }
        });
        jpanel4.add(lblProductImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 110, 176, 158));

        lblProductImage3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOrderProductMouseClicked(evt);
            }
        });
        jpanel4.add(lblProductImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 110, 176, 158));

        lblProductName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpanel4.add(lblProductName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 280, 176, 25));

        lblProductName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpanel4.add(lblProductName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 280, 176, 25));

        lblProductName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpanel4.add(lblProductName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, 176, 25));

        lblProductImage4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOrderProductMouseClicked(evt);
            }
        });
        jpanel4.add(lblProductImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 339, 176, 157));

        lblProductName4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpanel4.add(lblProductName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 503, 176, 25));

        lblProductImage5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOrderProductMouseClicked(evt);
            }
        });
        jpanel4.add(lblProductImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 339, 176, 157));

        lblProductImage6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOrderProductMouseClicked(evt);
            }
        });
        jpanel4.add(lblProductImage6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 339, 176, 157));

        lblProductName5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpanel4.add(lblProductName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 502, 176, 26));

        lblProductName6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpanel4.add(lblProductName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 502, 176, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblOrderProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrderProductMouseClicked
        JLabel lbl = (JLabel) evt.getSource();
        int index = Integer.parseInt(lbl.getName());
        System.out.println("You clicked on:" + index);

        if (index >= productList.size()) {
            JOptionPane.showMessageDialog(null, "Invalid Item Clicked");
            return;
        }

        String[] str = {"Add to Cart", "Order Now!"};
        int choice = JOptionPane.showOptionDialog(null, "What do you want do?", "Select", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, str, str[1]);
        if (choice == 0) {

            ProductPojo p = productList.get(index);
            PlaceOrderPojo ord = new PlaceOrderPojo();
            ord.setProductId(p.getProductId());
            ord.setCustomerId(UserProfile.getUserId().trim());
            ord.setCompanyId(p.getCompanyId());
            try {
                boolean result = OrderDAO.addToCart(ord);
                if (result) {
                    JOptionPane.showMessageDialog(null, "Product added to cart!!");
                    return;
                } else {
                    JOptionPane.showMessageDialog(null, "Cannot add the product to cart");
                    return;
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "DB Error while adding to cart");
                ex.printStackTrace();
            }

        } else {
            ProductPojo p = productList.get(index);
            showFrame = new OrderProductFrame(p);
            showFrame.setVisible(true);
            this.dispose();

        }

    }//GEN-LAST:event_lblOrderProductMouseClicked

    private void jcCompanyNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCompanyNamesActionPerformed

        listIndex = 0;
        String compName = jcCompanyNames.getSelectedItem().toString();
        String compId = companyMap.get(compName);
        if (compId == null) {
            compId = "ALL";
        }

        try {

            productList = ProductDAO.getAllProductsByCompanyId(compId);
            showDetails();

        } catch (SQLException sq) {
            JOptionPane.showMessageDialog(null, "DB Error in OrderFoodFrame");
            sq.printStackTrace();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Image Error in OrderFoodFrame");
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jcCompanyNamesActionPerformed

    private void lblNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseClicked

        if (listIndex > productList.size()) {

            JOptionPane.showMessageDialog(null, "No More Products to be displayed !");
            return;
        }
        showDetails();
    }//GEN-LAST:event_lblNextMouseClicked

    private void lblPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrevMouseClicked

        listIndex -= 12;
        if (listIndex < 0) {

            JOptionPane.showMessageDialog(null, "Already at 1st Item!");
            listIndex = 0;
            return;
        }
        showDetails();
    }//GEN-LAST:event_lblPrevMouseClicked

    private void btnMyAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyAccountActionPerformed
        CustomerAccountFrame accountFrame = new CustomerAccountFrame();
        accountFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMyAccountActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CustomerOptionFrame optionFrame = new CustomerOptionFrame();
        optionFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMyCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyCartActionPerformed
        new CustomerCartFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMyCartActionPerformed

    private void btnCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrderActionPerformed
        new CancelOrderFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelOrderActionPerformed

    private void btnOrderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderHistoryActionPerformed
        new OrderHistoryFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOrderHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderFoodFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnMyAccount;
    private javax.swing.JButton btnMyCart;
    private javax.swing.JButton btnOrderHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jcCompanyNames;
    private javax.swing.JPanel jpanel4;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblPrev;
    private javax.swing.JLabel lblProductImage1;
    private javax.swing.JLabel lblProductImage2;
    private javax.swing.JLabel lblProductImage3;
    private javax.swing.JLabel lblProductImage4;
    private javax.swing.JLabel lblProductImage5;
    private javax.swing.JLabel lblProductImage6;
    private javax.swing.JLabel lblProductName1;
    private javax.swing.JLabel lblProductName2;
    private javax.swing.JLabel lblProductName3;
    private javax.swing.JLabel lblProductName4;
    private javax.swing.JLabel lblProductName5;
    private javax.swing.JLabel lblProductName6;
    private javax.swing.JLabel lblUserProfileName;
    // End of variables declaration//GEN-END:variables

    private void loadCompanyNames() {

        try {

            companyMap = CompanyDAO.getAllCompanyIdAndName();
            Set<String> companyNames = companyMap.keySet();
            jcCompanyNames.addItem("ALL ");
            for (String cname : companyNames) {

                jcCompanyNames.addItem(cname);

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "DB Error in OrderFoodFrame");
            ex.printStackTrace();
        }

    }

    private void showDetails() {

        if (listIndex < productList.size()) {
            ProductPojo p = productList.get(listIndex);
            Image img = p.getProductImage();
            img = img.getScaledInstance(lblProductImage1.getWidth(), lblProductImage1.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            lblProductImage1.setIcon(icon);
            lblProductName1.setText(p.getProductName());
            lblProductImage1.setName(listIndex + "");
            lblProductName1.setName(listIndex + "");
            listIndex++;
        } else {

            lblProductImage1.setIcon(null);
            lblProductName1.setText("N/A");
            lblProductImage1.setText("N/A");
            lblProductImage1.setName(listIndex + "");
            lblProductName1.setName(listIndex + "");
            listIndex++;
        }

        if (listIndex < productList.size()) {
            ProductPojo p = productList.get(listIndex);
            Image img = p.getProductImage();
            img = img.getScaledInstance(lblProductImage2.getWidth(), lblProductImage2.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            lblProductImage2.setIcon(icon);
            lblProductName2.setText(p.getProductName());
            lblProductImage2.setName(listIndex + "");
            lblProductName2.setName(listIndex + "");
            listIndex++;
        } else {

            lblProductImage2.setIcon(null);
            lblProductName2.setText("N/A");
            lblProductImage2.setText("N/A");
            lblProductImage2.setName(listIndex + "");
            lblProductName2.setName(listIndex + "");
            listIndex++;
        }

        if (listIndex < productList.size()) {
            ProductPojo p = productList.get(listIndex);
            Image img = p.getProductImage();
            img = img.getScaledInstance(lblProductImage3.getWidth(), lblProductImage3.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            lblProductImage3.setIcon(icon);
            lblProductName3.setText(p.getProductName());
            lblProductImage3.setName(listIndex + "");
            lblProductName3.setName(listIndex + "");
            listIndex++;
        } else {

            lblProductImage3.setIcon(null);
            lblProductName3.setText("N/A");
            lblProductImage3.setText("N/A");
            lblProductImage3.setName(listIndex + "");
            lblProductName3.setName(listIndex + "");
            listIndex++;
        }

        if (listIndex < productList.size()) {
            ProductPojo p = productList.get(listIndex);
            Image img = p.getProductImage();
            img = img.getScaledInstance(lblProductImage4.getWidth(), lblProductImage4.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            lblProductImage4.setIcon(icon);
            lblProductName4.setText(p.getProductName());
            lblProductImage4.setName(listIndex + "");
            lblProductName4.setName(listIndex + "");
            listIndex++;
        } else {

            lblProductImage4.setIcon(null);
            lblProductName4.setText("N/A");
            lblProductImage4.setText("N/A");
            lblProductImage4.setName(listIndex + "");
            lblProductName4.setName(listIndex + "");
            listIndex++;
        }

        if (listIndex < productList.size()) {
            ProductPojo p = productList.get(listIndex);
            Image img = p.getProductImage();
            img = img.getScaledInstance(lblProductImage5.getWidth(), lblProductImage5.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            lblProductImage5.setIcon(icon);
            lblProductName5.setText(p.getProductName());
            lblProductImage5.setName(listIndex + "");
            lblProductName5.setName(listIndex + "");
            listIndex++;
        } else {

            lblProductImage5.setIcon(null);
            lblProductName5.setText("N/A");
            lblProductImage5.setText("N/A");
            lblProductImage5.setName(listIndex + "");
            lblProductName5.setName(listIndex + "");
            listIndex++;
        }

        if (listIndex < productList.size()) {
            ProductPojo p = productList.get(listIndex);
            Image img = p.getProductImage();
            img = img.getScaledInstance(lblProductImage6.getWidth(), lblProductImage6.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            lblProductImage6.setIcon(icon);
            lblProductName6.setText(p.getProductName());
            lblProductImage6.setName(listIndex + "");
            lblProductName6.setName(listIndex + "");
            listIndex++;
        } else {

            lblProductImage6.setIcon(null);
            lblProductName6.setText("N/A");
            lblProductImage6.setText("N/A");
            lblProductImage6.setName(listIndex + "");
            lblProductName6.setName(listIndex + "");
            listIndex++;

        }

    }
}
